"""TRT-LLM ArgTranslator: rewrites vLLM flags using ARG_MAP.

Coverage: every vLLM `serve` flag from repos/vllm/vllm/engine/arg_utils.py and
repos/vllm/vllm/entrypoints/openai/cli_args.py has an explicit decision below.
The set of flags `trtllm-serve` understands is much smaller than SGLang's (see
the click options in repos/trtllm/tensorrt_llm/commands/serve.py) - ~40
flags, all underscore-cased - so almost everything vLLM-side gets dropped.
A few well-known concepts have the obvious dash↔underscore rename.

YAML escape hatch: TRT-LLM exposes deeper LLM-API knobs through `--config
<yaml>` (extra-llm-api-options). Operators who need flags we drop here (seeds,
prefix caching toggles, eager mode, etc.) can pass them via that YAML; the
shim forwards `--config` unchanged.
"""

from collections.abc import Sequence

from vllm_shim.backend._shared import strip_optimization_level, translate_with_arg_map
from vllm_shim.backend.base.args import ArgTranslator

# vLLM flag => (trtllm_flag_or_None, has_value)
# None means "drop this flag (and its value if has_value)".
# Anything not listed here passes through verbatim, which only succeeds for
# flags that already use TRT-LLM's underscore convention - rare in practice.
ARG_MAP: dict[str, tuple[str | None, bool]] = {
    # === Renames: vLLM dash → TRT-LLM underscore, value forwarded unchanged ===
    "--tensor-parallel-size": ("--tp_size", True),
    "--tensor_parallel_size": ("--tp_size", True),
    "--pipeline-parallel-size": ("--pp_size", True),
    "--pipeline_parallel_size": ("--pp_size", True),
    "--max-model-len": ("--max_seq_len", True),
    "--max_model_len": ("--max_seq_len", True),
    "--max-num-seqs": ("--max_batch_size", True),
    "--max_num_seqs": ("--max_batch_size", True),
    "--max-num-batched-tokens": ("--max_num_tokens", True),
    "--max_num_batched_tokens": ("--max_num_tokens", True),
    # See docs/argument-translation.md for the gpu-memory-utilization caveat:
    # vLLM = fraction of total GPU memory; TRT-LLM = fraction of free memory
    # after weights/activations. Numeric value forwarded unchanged.
    "--gpu-memory-utilization": ("--kv_cache_free_gpu_memory_fraction", True),
    "--gpu_memory_utilization": ("--kv_cache_free_gpu_memory_fraction", True),
    "--trust-remote-code": ("--trust_remote_code", True),
    "--trust_remote_code": ("--trust_remote_code", True),
    "--served-model-name": ("--served_model_name", True),
    "--chat-template": ("--chat_template", True),
    "--revision": ("--hf_revision", True),
    "--hf-revision": ("--hf_revision", True),
    "--tokenizer": ("--tokenizer", True),
    "--kv-cache-dtype": ("--kv_cache_dtype", True),
    "--otlp-traces-endpoint": ("--otlp_traces_endpoint", True),
    "--reasoning-parser": ("--reasoning_parser", True),
    "--tool-call-parser": ("--tool_parser", True),
    "--media-io-kwargs": ("--media_io_kwargs", True),
    "--video-pruning-rate": ("--video_pruning_rate", True),
    # Renames boolean
    "--enable-chunked-prefill": ("--enable_chunked_prefill", False),

    # === Short aliases: rewrite to long form (TRT-LLM has no short flags) ===
    "-tp": ("--tp_size", True),
    "-pp": ("--pp_size", True),

    # === Default-already-matches: drop silently ===
    "--no-enable-chunked-prefill": (None, False),
    "--disable-log-requests": (None, False),
    "--disable-log-stats": (None, False),

    # === Engine knobs with no trtllm-serve equivalent: drop (with value) ===
    # Some have a YAML escape hatch via --config; see module docstring.
    "--additional-config": (None, True),
    "--all2all-backend": (None, True),
    "--allowed-local-media-path": (None, True),
    "--allowed-media-domains": (None, True),
    "--api-server-count": (None, True),
    "-asc": (None, True),
    "--attention-backend": (None, True),
    "--attention-config": (None, True),
    "-ac": (None, True),
    "--block-size": (None, True),
    "--code-revision": (None, True),
    "--collect-detailed-traces": (None, True),
    "--compilation-config": (None, True),
    "-cc": (None, True),
    "--config-format": (None, True),
    "--convert": (None, True),
    "--cp-kv-cache-interleave-size": (None, True),
    "--cudagraph-capture-sizes": (None, True),
    "--data-parallel-address": (None, True),
    "-dpa": (None, True),
    "--data-parallel-backend": (None, True),
    "-dpb": (None, True),
    "--data-parallel-rank": (None, True),
    "-dpn": (None, True),
    "--data-parallel-rpc-port": (None, True),
    "-dpp": (None, True),
    "--data-parallel-size": (None, True),
    "-dp": (None, True),
    "--data-parallel-size-local": (None, True),
    "-dpl": (None, True),
    "--data-parallel-start-rank": (None, True),
    "-dpr": (None, True),
    "--dbo-decode-token-threshold": (None, True),
    "--dbo-prefill-token-threshold": (None, True),
    "--dcp-comm-backend": (None, True),
    "--dcp-kv-cache-interleave-size": (None, True),
    "--decode-context-parallel-size": (None, True),
    "-dcp": (None, True),
    "--default-mm-loras": (None, True),
    "--distributed-executor-backend": (None, True),
    "--distributed-timeout-seconds": (None, True),
    "--download-dir": (None, True),
    "--dtype": (None, True),
    "--ec-transfer-config": (None, True),
    "--eplb-config": (None, True),
    "--expert-placement-strategy": (None, True),
    "--gdn-prefill-backend": (None, True),
    "--generation-config": (None, True),
    "--hf-config-path": (None, True),
    "--hf-overrides": (None, True),
    "--hf-token": (None, True),
    "--ignore-patterns": (None, True),
    "--io-processor-plugin": (None, True),
    "--ir-op-priority": (None, True),
    "--kernel-config": (None, True),
    "--kv-cache-dtype-skip-layers": (None, True),
    "--kv-cache-memory-bytes": (None, True),
    "--kv-cache-metrics-sample": (None, True),
    "--kv-events-config": (None, True),
    "--kv-offloading-backend": (None, True),
    "--kv-offloading-size": (None, True),
    "--kv-transfer-config": (None, True),
    "--limit-mm-per-prompt": (None, True),
    "--load-format": (None, True),
    "--logits-processors": (None, True),
    "--logprobs-mode": (None, True),
    "--long-prefill-token-threshold": (None, True),
    "--lora-dtype": (None, True),
    "--lora-modules": (None, True),
    "--lora-target-modules": (None, True),
    "--mamba-backend": (None, True),
    "--mamba-block-size": (None, True),
    "--mamba-cache-dtype": (None, True),
    "--mamba-cache-mode": (None, True),
    "--mamba-cache-philox-rounds": (None, True),
    "--mamba-ssm-cache-dtype": (None, True),
    "--master-addr": (None, True),
    "--master-port": (None, True),
    "--max-cpu-loras": (None, True),
    "--max-cudagraph-capture-size": (None, True),
    "--max-lora-rank": (None, True),
    "--max-logprobs": (None, True),
    "--max-long-partial-prefills": (None, True),
    "--max-loras": (None, True),
    "--max-num-partial-prefills": (None, True),
    "--max-parallel-loading-workers": (None, True),
    "--max-seq-len-to-capture": (None, True),
    "--mm-encoder-attn-backend": (None, True),
    "--mm-encoder-tp-mode": (None, True),
    "--mm-processor-cache-gb": (None, True),
    "--mm-processor-cache-type": (None, True),
    "--mm-processor-kwargs": (None, True),
    "--mm-shm-cache-max-object-size-mb": (None, True),
    "--model-impl": (None, True),
    "--model-loader-extra-config": (None, True),
    "--moe-backend": (None, True),
    "--nnodes": (None, True),
    "-n": (None, True),
    "--node-rank": (None, True),
    "-r": (None, True),
    "--num-cpu-blocks-override": (None, True),
    "--num-gpu-blocks-override": (None, True),
    "--numa-bind-cpus": (None, True),
    "--numa-bind-nodes": (None, True),
    "--offload-backend": (None, True),
    "--offload-group-size": (None, True),
    "--offload-num-in-group": (None, True),
    "--offload-prefetch-step": (None, True),
    "--optimization-level": (None, True),
    "--override-attention-dtype": (None, True),
    "--override-generation-config": (None, True),
    "--performance-mode": (None, True),
    "--pooler-config": (None, True),
    "--prefill-context-parallel-size": (None, True),
    "-pcp": (None, True),
    "--prefix-caching-hash-algo": (None, True),
    "--profiler-config": (None, True),
    "--pt-load-map-location": (None, True),
    "--quantization": (None, True),
    "-q": (None, True),
    "--reasoning-config": (None, True),
    "--reasoning-parser-plugin": (None, True),
    "--renderer-num-workers": (None, True),
    "--runner": (None, True),
    "--safetensors-load-strategy": (None, True),
    "--scheduler-cls": (None, True),
    "--scheduler-delay-factor": (None, True),
    "--scheduling-policy": (None, True),
    "--seed": (None, True),
    "--show-hidden-metrics-for-version": (None, True),
    "--shutdown-timeout": (None, True),
    "--speculative-config": (None, True),
    "-sc": (None, True),
    "--stream-interval": (None, True),
    "--structured-outputs-config": (None, True),
    "--swap-space": (None, True),
    "--tokenizer-mode": (None, True),
    "--tokenizer-revision": (None, True),
    "--tool-server": (None, True),
    "--ubatch-size": (None, True),
    "--weight-transfer-config": (None, True),
    "--worker-cls": (None, True),
    "--worker-extension-cls": (None, True),

    # === Engine knobs with no trtllm-serve equivalent: drop (boolean) ===
    "--aggregate-engine-logging": (None, False),
    "--allow-deprecated-quantization": (None, False),
    "--async-scheduling": (None, False),
    "--calculate-kv-scales": (None, False),
    "--cpu-offload-gb": (None, False),
    "--cpu-offload-params": (None, False),
    "--cudagraph-metrics": (None, False),
    "--data-parallel-external-lb": (None, False),
    "-dpe": (None, False),
    "--data-parallel-hybrid-lb": (None, False),
    "-dph": (None, False),
    "--disable-cascade-attn": (None, False),
    "--disable-chunked-mm-input": (None, False),
    "--disable-custom-all-reduce": (None, False),
    "--disable-hybrid-kv-cache-manager": (None, False),
    "--disable-nccl-for-dp-synchronization": (None, False),
    "--disable-sliding-window": (None, False),
    "--enable-dbo": (None, False),
    "--enable-elastic-ep": (None, False),
    "--enable-ep-weight-filter": (None, False),
    "--enable-eplb": (None, False),
    "--enable-expert-parallel": (None, False),
    "-ep": (None, False),
    "--enable-flashinfer-autotune": (None, False),
    "--enable-layerwise-nvtx-tracing": (None, False),
    "--enable-log-requests": (None, False),
    "--enable-lora": (None, False),
    "--enable-mamba-cache-stochastic-rounding": (None, False),
    "--enable-mfu-metrics": (None, False),
    "--enable-mm-embeds": (None, False),
    "--enable-multi-modal": (None, False),
    "--enable-prefix-caching": (None, False),
    "--enable-prompt-adapter": (None, False),
    "--enable-prompt-embeds": (None, False),
    "--enable-return-routed-experts": (None, False),
    "--enable-sleep-mode": (None, False),
    "--enable-tower-connector-lora": (None, False),
    "--enforce-eager": (None, False),
    "--enforce_eager": (None, False),
    "--fail-on-environ-validation": (None, False),
    "--fully-sharded-loras": (None, False),
    "--grpc": (None, False),
    "--headless": (None, False),
    "--interleave-mm-strings": (None, False),
    "--kv-cache-metrics": (None, False),
    "--kv-sharing-fast-prefill": (None, False),
    "--language-model-only": (None, False),
    "--mm-encoder-only": (None, False),
    "--mm-tensor-ipc": (None, False),
    "--no-enable-prefix-caching": (None, False),
    "--numa-bind": (None, False),
    "--offload-params": (None, False),
    "--ray-workers-use-nsight": (None, False),
    "--scheduler-reserve-full-isl": (None, False),
    "--skip-mm-profiling": (None, False),
    "--skip-tokenizer-init": (None, False),
    "--specialize-active-lora": (None, False),
    "--use-tqdm-on-load": (None, False),

    # === Frontend HTTP server flags handled by haproxy/middleware in the shim,
    # not by the engine. (api-key, ssl-keyfile/certfile/ca-certs, host, port
    # are common to vLLM and trtllm-serve and pass through.) ===
    "--allow-credentials": (None, False),
    "--allowed-headers": (None, True),
    "--allowed-methods": (None, True),
    "--allowed-origins": (None, True),
    "--chat-template-content-format": (None, True),
    "--default-chat-template-kwargs": (None, True),
    "--disable-access-log-for-endpoints": (None, True),
    "--disable-fastapi-docs": (None, False),
    "--disable-uvicorn-access-log": (None, False),
    "--enable-auto-tool-choice": (None, False),
    "--enable-flash-late-interaction": (None, False),
    "--enable-force-include-usage": (None, False),
    "--enable-log-deltas": (None, False),
    "--enable-log-outputs": (None, False),
    "--enable-logging-iteration-details": (None, False),
    "--enable-offline-docs": (None, False),
    "--enable-prompt-tokens-details": (None, False),
    "--enable-request-id-headers": (None, False),
    "--enable-server-load-tracking": (None, False),
    "--enable-ssl-refresh": (None, False),
    "--enable-tokenizer-info-endpoint": (None, False),
    "--exclude-tools-when-tool-choice-none": (None, False),
    "--h11-max-header-count": (None, True),
    "--h11-max-incomplete-event-size": (None, True),
    "--log-config-file": (None, True),
    "--log-error-stack": (None, False),
    "--max-log-len": (None, True),
    "--middleware": (None, True),  # vLLM and TRT-LLM both have one but values diverge
    "--response-role": (None, True),
    "--return-tokens-as-token-ids": (None, False),
    "--root-path": (None, True),
    "--ssl-cert-reqs": (None, True),
    "--ssl-ciphers": (None, True),
    "--tokens-only": (None, False),
    "--tool-parser-plugin": (None, True),
    "--trust-request-chat-template": (None, False),
    "--uds": (None, True),
    "--uvicorn-log-level": (None, True),
}


class TRTLLMArgTranslator(ArgTranslator):
    """Pure function over argv: rename, drop, or pass through each token per ARG_MAP."""

    def translate(self, vllm_args: Sequence[str]) -> tuple[list[str], list[str]]:
        a1, d1 = strip_optimization_level(list(vllm_args))
        translated, d2 = translate_with_arg_map(a1, ARG_MAP)
        return translated, d1 + d2
